name: watertap-ui-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - nodejs=16
  - pip:
    - -r backend/requirements.txt
    - git+https://github.com/watertap-org/watertap@17504c91a311298a848b1e92dcab64f4acdbbc3c
