name: App Tests

on:
  push:
    branches:
      - main
      - rel_*
  pull_request:

defaults:
  run:
    # -l: use login shell (required when using Conda)
    shell: bash -l {0}

jobs:
  component_e2e_testing:
    name: E2E testing (${{ matrix.os }})

    runs-on: ${{ matrix.os-version }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - linux
          - win64
          # - macos
        include:
          - os: linux
            os-version: ubuntu-latest
          - os: win64
            os-version: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: watertap-ui-env

      - name: Install JS dependencies
        run: |
          echo "::group::Show info for NPM, etc"
          which npm
          npm --version
          echo "::endgroup::"
          (cd electron && npm clean-install)
          (cd electron/ui && npm clean-install)

      - name: get idaes extensions
        working-directory: backend/app
        run: idaes get-extensions

      - name: run backend server
        working-directory: backend/app
        run: uvicorn main:app --reload --host 0.0.0.0 --port 8001 &

      - name: run frontend
        working-directory: electron/ui
        run: npm start &

      - name: Cypress e2e tests
        working-directory: electron
        run: |
          # which cypress ; cypress --version
          cypress run

      - name: Upload artifact for screenshots & videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
            name: cypress_results-${{ matrix.os }}
            path: |
              electron/cypress/screenshots/
              electron/cypress/videos/
